# Generated by Django 3.0.6 on 2020-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12)),
                ("title", models.CharField(max_length=50)),
                ("version", models.CharField(blank=True, max_length=25, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
